# file: oracle-jdk/meta/main.yml

galaxy_info:
  author: Marcelo Correia
  company: Star Visitor
  description: "Installs latest Docker from docker.io"
  min_ansible_version: 1.7
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
  - development

dependencies: []
