---
# handlers file for ansible-docker

- name: 'start docker'
  sudo: yes
  service: name=docker state=started
  tags:
    - init

- name: 'restart docker'
  sudo: yes
  service: name=docker state=restarted
