---
resources:
  - name: git-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}

jobs:
  - name: packer-bare-base
    serial: true
    public: true
    plan:
      - get: git-repo-master
        trigger: true

