---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: git-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}
  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}
  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack_webook}}

jobs:
  - name: packer-concourse
    serial: true
    plan:
      - get: git-repo-master
      - put: resource_version
        params:
          bump: patch
      - task: validate
        file: git-repo-master/cicd/validate.yml
        params:
          AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
          AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      - task: bake
        file: git-repo-master/cicd/bake.yml
        params:
          AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
          AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
    on_failure:
      put: slack-alert
      params:
        channel: '#ci'
        text: |
          Build $BUILD_NAME. *$BUILD_JOB_NAME* failed!
          Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_success:
      put: slack-alert
      params:
        channel: '#ci'
        text: |
          :white_check_mark: $BUILD_PIPELINE_NAME has a new release.
          Check it out at:
          https://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME



