---
resources:
  - name: git-repo-master
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      private_key: {{git_private_key}}
      username: {{github_user}}
  - name: resource_version
    type: semver
    source:
      driver: git
      initial_version: 0.1.0
      uri: {{git_repo_url}}
      branch: version
      file: version
      private_key: {{git_private_key}}
      username: {{github_user}}

jobs:
  - name: packer-bare-base
    serial: true
    public: true
    plan:
      - get: git-repo-master
        trigger: true
      - put: resource_version
        params:
          - bump: {{version_bump}}


